version: '3.8'

services:
  client:
    image: rshdfs-client
    hostname: client
    volumes:
      - ./config/client.xml:/config/client.xml
  namenode:
    image: rshdfs-namenode
    hostname: namenode  # Set the hostname for the NameNode
    ports:
      - "50000:50000"
    volumes:
      - ./config/namenode.xml:/config/namenode.xml
      - namenode-data:/hdfs/namenode

  datanode1:
    image: rshdfs-datanode
    ports:
      - "50002:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode1-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

  datanode2:
    image: rshdfs-datanode
    ports:
      - "50003:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode2-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

  datanode3:
    image: rshdfs-datanode
    ports:
      - "50004:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode3-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:
