version: '3.8'

services:
  namenode:
    image: rshdfs-namenode
    hostname: namenode  # Set the hostname for the NameNode
    ports:
      - "50000:50000"
    volumes:
      - ./config/namenode.xml:/config/namenode.xml
      - namenode-data:/hdfs/namenode

  datanode:
    image: rshdfs-datanode
    ports:
      - "50002:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

volumes:
  namenode-data:
  datanode-data:
