version: '3.8'

services:
  client:
    image: rshdfs
    hostname: rshdfs
    volumes:
      - ./config/rshdfs.xml:/config/rshdfs.xml
      - client-tmp:/tmp
  client2:
    image: rshdfs
    hostname: rshdfs2
    volumes:
      - ./config/rshdfs.xml:/config/rshdfs.xml
      - client2-tmp:/tmp
  namenode:
    image: namenode
    hostname: namenode  # Set the hostname for the NameNode
    ports:
      - "50000:50000"
    volumes:
      - ./config/namenode.xml:/config/namenode.xml
      - namenode-data:/hdfs/namenode

  datanode1:
    image: datanode
    hostname: datanode1
    ports:
      - "50002:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode1-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

  datanode2:
    image: datanode
    hostname: datanode2
    ports:
      - "50003:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode2-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

  datanode3:
    hostname: datanode3
    image: datanode
    ports:
      - "50004:50002"
    volumes:
      - ./config/datanode.xml:/config/datanode.xml
      - datanode3-data:/hdfs/data
    environment:
      - NAMENODE_HOST=namenode

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:
  client-tmp:
  client2-tmp:
